### ISSUE TITLE
Why does it only seem to output JPEGs?

### ISSUE THREAD

**Issue by IllusionSector** [alexd3rsan/rollingshutterpy#3]
And pretty over-compressed, low quality JPEGs at that.

**Comment by alexd3rsan** [comment]
@IllusionSector 
Why JPEG?: Because I originally tested it that way first.
There's no good reason for it to only allow _lossy_ JPEG files.

I also didn't realize the high level of compression until now.
It turns out the standard quality level used by 'Image.save()' is 75.

In retrospect a lossless filetype would've been a better choice, so thanks for your input!

I've introduced a global 'IMAGE_QUALITY' variable and set the standard value to 95 instead of the aforementioned 75.

PNG will be the default filetype from now on. Additionally, JPEG will stay a supported, yet optional, output filetype.

**Comment by IllusionSector** [comment]
Thank you so very much for the update, Alex.
That rocked.
